export const LIMITS = {
  CATEGORIES_LIMITS: 18,
  PRODUCTS_LIMITS: 30,
  RELATED_PRODUCTS_LIMITS: 15,
  BEST_SELLER_PRODUCTS_LIMITS: 15,
  BEST_SELLER_GROCERY_PRODUCTS_LIMITS: 21,
  POPULAR_PRODUCTS_LIMITS: 14,
  POPULAR_PRODUCTS_TWO_LIMITS: 10,
  SEARCH_PRODUCTS_LIMITS: 6,
};
