export const bundleData = [
  {
    id: 1,
    slug: '404',
    image: '/assets/images/bundle/5.png',
    title: 'bundle-title-one',
    description: 'bundle-description',
  },
  {
    id: 2,
    slug: '404',
    image: '/assets/images/bundle/6.png',
    title: 'bundle-title-two',
    description: 'bundle-description',
  },
  {
    id: 3,
    slug: '404',
    image: '/assets/images/bundle/7.png',
    title: 'bundle-title-three',
    description: 'bundle-description',
  },
  {
    id: 4,
    slug: '404',
    image: '/assets/images/bundle/8.png',
    title: 'bundle-title-four',
    description: 'bundle-description',
  },
  {
    id: 5,
    slug: '404',
    image: '/assets/images/bundle/9.png',
    title: 'bundle-title-one',
    description: 'bundle-description',
  },
  {
    id: 6,
    slug: '404',
    image: '/assets/images/bundle/10.png',
    title: 'bundle-title-two',
    description: 'bundle-description',
  },
  {
    id: 7,
    slug: '404',
    image: '/assets/images/bundle/11.png',
    title: 'bundle-title-three',
    description: 'bundle-description',
  },
  {
    id: 8,
    slug: '404',
    image: '/assets/images/bundle/12.png',
    title: 'bundle-title-four',
    description: 'bundle-description',
  },
  {
    id: 9,
    slug: '404',
    image: '/assets/images/bundle/13.png',
    title: 'bundle-title-one',
    description: 'bundle-description',
  },
  {
    id: 10,
    slug: '404',
    image: '/assets/images/bundle/14.png',
    title: 'bundle-title-two',
    description: 'bundle-description',
  },
  {
    id: 11,
    slug: '404',
    image: '/assets/images/bundle/15.png',
    title: 'bundle-title-three',
    description: 'bundle-description',
  },
  {
    id: 12,
    slug: '404',
    image: '/assets/images/bundle/16.png',
    title: 'bundle-title-four',
    description: 'bundle-description',
  },
];

export const bundleDataTwo = [
  {
    id: 1,
    slug: '404',
    image: '/assets/images/bundle/1.png',
    title: 'bundle-title-one',
    description: 'bundle-description',
    bgColor: '#FFEED6',
  },
  {
    id: 2,
    slug: '404',
    image: '/assets/images/bundle/2.png',
    title: 'bundle-title-two',
    description: 'bundle-description',
    bgColor: '#D6D2EC',
  },
  {
    id: 3,
    slug: '404',
    image: '/assets/images/bundle/3.png',
    title: 'bundle-title-three',
    description: 'bundle-description',
    bgColor: '#DBE5EF',
  },
  {
    id: 4,
    slug: '404',
    image: '/assets/images/bundle/4.png',
    title: 'bundle-title-four',
    description: 'bundle-description',
    bgColor: '#EFD8D4',
  },
];
export const bundleDataThree = [
  {
    id: 1,
    slug: '404',
    image: '/assets/images/bundle/17.png',
    title: 'bundle-title-five',
  },
  {
    id: 2,
    slug: '404',
    image: '/assets/images/bundle/18.png',
    title: 'bundle-title-six',
  },
  {
    id: 3,
    slug: '404',
    image: '/assets/images/bundle/19.png',
    title: 'bundle-title-seven',
  },
];
